version: '3'

services:
  nginx:
    image: nginx:1.17.0-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    env_file: .env
    volumes:
      - data-wp:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./wordpress/theme:/var/www/html/wp-content/themes/headless:ro
    networks:
      - proxy
      - default

  wordpress:
    build: ./wordpress
    expose:
      - 9000
    restart: always
    env_file: .env
    volumes:
      - data-wp:/var/www/html:rw
      - ./wordpress/default.ini:/usr/local/etc/php/conf.d/default.ini:ro
      - ./wordpress/php.ini:/usr/local/etc/php/php.ini:ro
      - ./wordpress/theme:/var/www/html/wp-content/themes/headless:ro
    networks:
      - default

  mysql:
    image: mysql:5.7.19
    expose:
      - 3306
    restart: always
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql:rw
    networks:
      - default

  wpcli:
    image: tatemz/wp-cli
    volumes:
      - data-wp:/var/www/html:rw
      - data-db:/var/lib/mysql:rw
      - ./backup:/backup:rw
      - ./wordpress/theme:/var/www/html/wp-content/themes/headless:ro
    # entrypoint: wp
    working_dir: /
    command: '--info'
    networks:
      - default

volumes:
  data-wp:
    external:
      name: ${VOLUME_NAME}-wp
  data-db:
    external:
      name: ${VOLUME_NAME}-db

networks:
  default:
  proxy:
    external:
      name: ${NETWORK_PROXY_NAME}
