version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10.0

    working_directory: ~/brdr-log

    # developからのPull Requestの時だけCircleCIを動かす
    # CircleCIのプロジェクト設定の、Advanced Settings -> Only build pull requests をOnに
    branches:
      ignore:
        - master
        - /feature-.*/

    steps:
      - checkout

      - restore_cache:
          keys:
            - brdr-log-{{ checksum "theme/package.json" }}

      - run:
          name: Install Node Package
          command: |
            cd theme
            npm install

      - save_cache:
          key: brdr-log-{{ checksum "theme/package.json" }}
          paths:
            - ./theme/node_modules

      - run:
          name: Test
          command: |
            cd theme
            npm run lint
