version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10.0

    working_directory: ~/brdr-log

    # developからのPull Requestの時だけCircleCIを動かす
    # CircleCIのプロジェクト設定の、Advanced Settings -> Only build pull requests をOnに
    branches:
      only:
        - develop

    steps:
      - checkout

      - restore_cache:
          keys:
            - brdr-log-{{ checksum "package.json" }}

      - run:
          name: Install Node Package
          command: npm install

      - save_cache:
          key: brdr-log-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Test
          command: npm run lint
