version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10.0

    branches:
      only:
        - master

    working_directory: /tmp/brdr-log

    steps:
      - checkout

      - run:
        name: Move Theme Directory
        command: cd theme

      # Download and cache dependencies
      - restore_cache:
        keys:
          - dependency-cache-{{ checksum "package.json" }}
          - dependency-cache-

      - run:
        name: Install Node Package
        command: npm install

      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules

      - run:
        name: Lint
        command: npm run lint

      - run:
        name: Build
        command: npm run build
