# CircleCIのプロジェクト設定の、Advanced Settings -> Only build pull requestsをOnに
version: 2

defaults: &defaults
  working_directory: ~/brdr-log
  docker:
    - image: circleci/node:7.10.0

jobs:
  # install npm package
  # build というjob名にしないとエラーが出る
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - brdr-log-{{ checksum "package.json" }}

      - run:
          name: Install node package
          command: npm install

      - save_cache:
          key: brdr-log-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  # lint
  lint-js-css:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Lint
          command: npm run lint

  # build and publish
  build-and-publish:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Build
          command: npm run build

      - run:
          name: Erase and move files
          command: |
            find . -maxdepth 1 -type f -not -name '.gitmodules' | xargs rm -rf
            find . -maxdepth 1 -type d -not -name '.' -not -name '.git' -not -name 'server' -not -name 'dist' | xargs rm -rf
            mv dist theme

      - deploy:
          name: Deploy and publich
          command: |
            - git config --global user.name  "CircleCI"
            - git config --global user.email "circleci@log.brdr.jp"
            - git add .
            - git commit -m "[ci skip] Publish by CircleCI"
            - git checkout -B public
            - git push -u origin public --force

workflows:
  version: 2

  test-or-deploy:
    jobs:
      # developからmasterへのpull requestが作成されたとき
      # masterへpull requestがmergeされたとき
      - build:
          filters:
            branches:
              only:
                - develop
                - master

      # developからmasterへのpull requestが作成されたとき
      - lint-js-css:
          requires:
            - build
          filters:
            branches:
              only: develop

      # masterへpull requestがmergeされたとき
      - build-and-publish:
          requires:
            - build
          filters:
            branches:
              only: master
